spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL:}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:}}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: true

server:
  address: 0.0.0.0
  port: ${PORT:10000}
  forward-headers-strategy: framework

logging:
  level:
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:OFF}

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}
