spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:${MAIDAV_PROD_DB_PORT:5435}/${MAIDAV_PROD_DB_NAME:sales_db}
    username: ${MAIDAV_PROD_DB_USERNAME:sales}
    password: ${MAIDAV_PROD_DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${MAIDAV_PROD_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: America/Argentina/Buenos_Aires

  jackson:
    time-zone: America/Argentina/Buenos_Aires

  flyway:
    enabled: ${MAIDAV_PROD_FLYWAY_ENABLED:false}
    baseline-on-migrate: true

  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:OFF}

app:
  upload-dir: uploads
