spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:${MAIDAV_TESTING_DB_PORT:5434}/${MAIDAV_TESTING_DB_NAME:sales_db}
    username: ${MAIDAV_TESTING_DB_USERNAME:sales}
    password: ${MAIDAV_TESTING_DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${MAIDAV_TESTING_SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: America/Argentina/Buenos_Aires

  jackson:
    time-zone: America/Argentina/Buenos_Aires

  flyway:
    enabled: ${MAIDAV_TESTING_FLYWAY_ENABLED:true}
    baseline-on-migrate: true

  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:DEBUG}

app:
  upload-dir: uploads
